;;; -*- Mode: Lisp; Syntax: Common-Lisp -*-
;;;
;;; agent-orrery.asd — System definitions for Agent Orrery
;;;

(defsystem "agent-orrery/coalton"
  :description "Coalton pure-core baseline for Agent Orrery"
  :version "0.1.0"
  :license "MIT"
  :depends-on ("coalton" "named-readtables")
  :serial t
  :components
  ((:module "src"
    :serial t
    :components
    ((:file "packages")
     (:module "coalton"
      :serial t
      :components ((:file "core")
                   (:file "policy")
                   (:file "configuration")
                   (:file "usage-analytics")
                   (:file "anomaly-detector")
                   (:file "budget-policy")
                   (:file "notification-routing")
                   (:file "session-lifecycle")
                   (:file "scenario-planning")
                   (:file "audit-trail")
                   (:file "cost-optimizer")
                   (:file "capacity-planner")
                   (:file "session-analytics")))))))

(defsystem "agent-orrery"
  :description "Dashboard for OpenClaw-compatible agent systems"
  :version "0.1.0"
  :license "MIT"
  :depends-on ("agent-orrery/coalton" "dexador" "com.inuoe.jzon" "croatoan" "hunchentoot" "mcclim")
  :serial t
  :components
  ((:module "src"
    :serial t
    :components
    ((:file "packages")
     (:module "domain"
      :components ((:file "types")))
     (:module "protocol-schema"
      :serial t
      :components ((:file "package")
                   (:file "types")
                   (:file "validators")
                   (:file "serialization")))
     (:module "adapter"
      :components ((:file "protocol")
                   (:file "generic-starter-kit")
                   (:file "openclaw")
                   (:file "contract-probe")
                   (:file "html-fallback")
                   (:file "capability-mapper")
                   (:file "endpoint-classifier")
                   (:file "handshake-probe")
                   (:file "capability-contract")
                   (:file "preflight")
                   (:file "gate-runner")
                   (:file "preflight-json")
                   (:file "contract-harness")
                   (:file "probe-orchestrator")
                   (:file "compatibility-report")
                   (:file "conformance-matrix")
                   (:file "transcript-capture")
                   (:file "schema-drift")
                   (:file "evidence-bundle")
                   (:file "gate-decision")
                   (:file "gate-orchestrator")
                   (:file "interface-matrix")
                   (:file "decision-core")
                   (:file "schema-compat")
                   (:file "replay-harness")
                   (:file "gate-invariant")
                   (:file "schema-gen")
                   (:file "replay-artifact")
                   (:file "runtime-transport")
                   (:file "capture-driver")
                   (:file "fixture-replay-compiler")
                   (:file "evidence-pack")
                   (:file "snapshot-drift")
                   (:file "health-monitor")
                   (:file "capture-differ")
                   (:file "decision-audit")
                   (:file "action-intent")
                   (:file "event-trace-canon")
                   (:file "parity-assertion")
                   (:file "fixture-corpus-gen")
                   (:file "gate-orchestration-runner")
                   (:file "usage-analytics-bridge")
                   (:file "anomaly-detector")
                   (:file "observability-trace-contract")
                   (:file "cross-ui-evidence-verifier")
                   (:file "playwright-evidence-compiler")
                   (:file "playwright-artifact-canonicalizer")
                   (:file "mcp-tui-evidence-compiler")
                   (:file "tui-scenario-ledger")
                   (:file "playwright-scenario-ledger")
                   (:file "playwright-evidence-notarizer")
                   (:file "epic4-fail-closed-gate")
                   (:file "evidence-manifest-lock")
                   (:file "tui-artifact-diff-checker")
                   (:file "epic-closure-gate")
                   (:file "evidence-recertification-gate")
                   (:file "epic-done-state-guard")
                   (:file "cross-ui-parity-suite")
                   (:file "performance-soak")
                   (:file "resilience-suite")
                   (:file "scenario-planning-bridge")
                   (:file "v2-projection-bridge")
                   (:file "evidence-manifest-validator")
                   (:file "tui-scenario-contracts")
                   (:file "ui-protocol-boundary")
                   (:file "replay-protocol-bridge")
                   (:file "ui-protocol-schema")
                   (:file "adapter-contract-checker")
                   (:file "boundary-declaration-gate")
                   (:file "design-doc-sync-gate")))
     (:module "pipeline"
      :components ((:file "events")
                   (:file "normalize")))
     (:module "store"
      :components ((:file "sync")))
     (:module "provider"
      :components ((:file "tui")))
     (:module "tui"
      :serial t
      :components ((:file "packages")
                   (:file "layout")
                   (:file "keys")
                   (:file "state")
                   (:file "render")
                   (:file "session-detail")
                   (:file "cron-ops")
                   (:file "analytics")
                   (:file "shell")))
     (:module "web"
      :serial t
      :components ((:file "packages")
                   (:file "views")
                   (:file "api")
                   (:file "server")))
     (:module "plugin"
      :serial t
      :components ((:file "packages")
                   (:file "sdk")
                   (:file "conformance")))
     (:module "mcclim"
      :serial t
      :components ((:file "packages")
                   (:file "frame")
                   (:file "commands")
                   (:file "inspectors")
                   (:file "e2e-gate")
                   (:file "v2-panes")))))))

(defsystem "agent-orrery/test-harness"
  :description "Deterministic fixture runtime harness for Agent Orrery"
  :version "0.1.0"
  :license "MIT"
  :depends-on ("agent-orrery" "parachute" "ironclad" "babel")
  :serial t
  :components
  ((:module "test-harness"
    :serial t
    :components
    ((:file "packages")
     (:file "clock")
     (:file "timeline")
     (:file "generators")
     (:file "conformance")
     (:file "fixture-adapter")
     (:module "tests"
      :components ((:file "harness-tests")
                   (:file "openclaw-adapter-tests")
                   (:file "generic-starter-kit-tests")
                   (:file "pipeline-store-tests")
                   (:file "conformance-tests")
                   (:file "contract-probe-tests")
                   (:file "normalization-tests")
                   (:file "coalton-core-tests")
                   (:file "configuration-tests")
                   (:file "html-fallback-tests")
                   (:file "capability-mapper-tests")
                   (:file "endpoint-classifier-tests")
                   (:file "policy-algebra-tests")
                   (:file "handshake-probe-tests")
                   (:file "policy-law-checks")
                   (:file "../fixtures/live-gate-corpus")
                   (:file "live-gate-contract-tests")
                   (:file "capability-contract-tests")
                   (:file "preflight-tests")
                   (:file "contract-harness-tests")
                   (:file "probe-orchestrator-tests")
                   (:file "conformance-matrix-tests")
                   (:file "transcript-capture-tests")
                   (:file "schema-drift-tests")
                   (:file "evidence-bundle-tests")
                   (:file "gate-decision-tests")
                   (:file "gate-orchestrator-tests")
                   (:file "interface-matrix-tests")
                   (:file "decision-core-tests")
                   (:file "schema-compat-tests")
                   (:file "replay-harness-tests")
                   (:file "gate-invariant-tests")
                   (:file "schema-gen-tests")
                   (:file "replay-artifact-tests")
                   (:file "runtime-transport-tests")
                   (:file "capture-driver-tests")
                   (:file "fixture-replay-compiler-tests")
                   (:file "evidence-pack-tests")
                   (:file "snapshot-drift-tests")
                   (:file "health-monitor-tests")
                   (:file "capture-differ-tests")
                   (:file "decision-audit-tests")
                   (:file "usage-analytics-tests")
                   (:file "anomaly-detector-tests")
                   (:file "plugin-sdk-tests")
                   (:file "plugin-conformance-tests")
                   (:file "budget-policy-tests")
                   (:file "notification-routing-tests")
                   (:file "event-trace-canon-tests")
                   (:file "parity-assertion-tests")
                   (:file "fixture-corpus-gen-tests")
                   (:file "gate-orchestration-runner-tests")
                   (:file "action-intent-tests")
                   (:file "tui-provider-tests")
                   (:file "web-api-protocol-tests")
                   (:file "tui-session-detail-tests")
                   (:file "tui-shell-tests")
                   (:file "session-lifecycle-tests")
                   (:file "tui-cron-ops-tests")
                   (:file "tui-analytics-tests")
                   (:file "mcclim-frame-tests")
                   (:file "mcclim-commands-tests")
                   (:file "mcclim-inspectors-tests")
                   (:file "mcclim-accessibility-tests")
                   (:file "mcclim-e2e-gate-tests")
                   (:file "observability-trace-contract-tests")
                   (:file "cross-ui-evidence-verifier-tests")
                   (:file "playwright-evidence-compiler-tests")
                   (:file "playwright-artifact-canonicalizer-tests")
                   (:file "mcp-tui-evidence-compiler-tests")
                   (:file "tui-scenario-ledger-tests")
                   (:file "playwright-scenario-ledger-tests")
                   (:file "playwright-evidence-notarizer-tests")
                   (:file "epic4-fail-closed-gate-tests")
                   (:file "tui-artifact-diff-checker-tests")
                   (:file "epic-closure-gate-tests")
                   (:file "evidence-recertification-gate-tests")
                   (:file "epic-done-state-guard-tests")
                   (:file "cross-ui-parity-suite-tests")
                   (:file "performance-soak-tests")
                   (:file "resilience-suite-tests")
                   (:file "scenario-planning-tests")
                   (:file "evidence-manifest-validator-tests")
                   (:file "tui-scenario-contracts-tests")
                   (:file "audit-trail-tests")
                   (:file "cost-optimizer-tests")
                   (:file "capacity-planner-tests")
                   (:file "session-analytics-tests")
                   (:file "tui-cost-capacity-cards-tests")
                   (:file "mcclim-v2-panes-tests")
                   (:file "plugin-lifecycle-hooks-tests")
                   (:file "v2-projection-bridge-tests")
                   (:file "ui-protocol-boundary-tests")
                   (:file "replay-protocol-bridge-tests")
                   (:file "ui-protocol-schema-tests")
                   (:file "protocol-schema-skeleton-tests")
                   (:file "adapter-contract-checker-tests")
                   (:file "boundary-declaration-gate-tests")
                   (:file "design-doc-sync-gate-tests")))))))
