;;; -*- Mode: Lisp; Syntax: Common-Lisp -*-
(in-package #:orrery/harness-tests)

(define-test event-trace-canon)

(define-test (event-trace-canon canonicalize-single)
  (let ((ev (canonicalize-event :adapter :session 1000 "payload-1")))
    (is = 1000 (tev-timestamp ev))
    (is eq :adapter (tev-source-tag ev))
    (is eq :session (tev-event-kind ev))
    (true (> (tev-seq-id ev) 0))
    (true (> (tev-payload-hash ev) 0))))

(define-test (event-trace-canon deterministic-id)
  (let ((e1 (canonicalize-event :adapter :session 1000 "payload"))
        (e2 (canonicalize-event :adapter :session 1000 "payload")))
    (is = (tev-seq-id e1) (tev-seq-id e2))
    (is = (tev-payload-hash e1) (tev-payload-hash e2))))

(define-test (event-trace-canon different-payloads)
  (let ((e1 (canonicalize-event :adapter :session 1000 "payload-a"))
        (e2 (canonicalize-event :adapter :session 1000 "payload-b")))
    (isnt = (tev-payload-hash e1) (tev-payload-hash e2))))

(define-test (event-trace-canon stream-sorted)
  (let* ((e1 (canonicalize-event :adapter :session 2000 "p1"))
         (e2 (canonicalize-event :pipeline :cron 1000 "p2"))
         (e3 (canonicalize-event :store :health 3000 "p3"))
         (stream (canonicalize-stream (list e1 e2 e3))))
    (is = 3 (ts-count stream))
    ;; first event should be timestamp 1000
    (is = 1000 (tev-timestamp (first (ts-events stream))))
    ;; last should be 3000
    (is = 3000 (tev-timestamp (car (last (ts-events stream)))))))

(define-test (event-trace-canon stream-dedup)
  (let* ((e1 (canonicalize-event :adapter :session 1000 "same"))
         (e2 (canonicalize-event :adapter :session 1000 "same"))
         (stream (canonicalize-stream (list e1 e2))))
    (is = 1 (ts-count stream))))

(define-test (event-trace-canon diff-identical)
  (let* ((e1 (canonicalize-event :adapter :session 1000 "p1"))
         (e2 (canonicalize-event :pipeline :cron 2000 "p2"))
         (s1 (canonicalize-stream (list e1 e2)))
         (s2 (canonicalize-stream (list e1 e2)))
         (diff (trace-diff s1 s2)))
    (is = 2 (tdr-matched-count diff))
    (is = 0 (tdr-mismatched-count diff))
    (is = 0 (tdr-missing-left diff))
    (is = 0 (tdr-missing-right diff))
    (true (trace-parity-p s1 s2))))

(define-test (event-trace-canon diff-missing)
  (let* ((e1 (canonicalize-event :adapter :session 1000 "p1"))
         (e2 (canonicalize-event :pipeline :cron 2000 "p2"))
         (e3 (canonicalize-event :store :health 3000 "p3"))
         (s1 (canonicalize-stream (list e1 e2)))
         (s2 (canonicalize-stream (list e1 e2 e3)))
         (diff (trace-diff s1 s2)))
    (is = 2 (tdr-matched-count diff))
    (is = 1 (tdr-missing-left diff))
    (false (trace-parity-p s1 s2))))

(define-test (event-trace-canon diff-mismatch)
  (let* ((e1a (canonicalize-event :adapter :session 1000 "payload-v1"))
         (e1b (canonicalize-event :adapter :session 1000 "payload-v2"))
         (s1 (canonicalize-stream (list e1a)))
         (s2 (canonicalize-stream (list e1b))))
    ;; Different payloads at same coords → different seq-ids → missing
    (false (trace-parity-p s1 s2))))

(define-test (event-trace-canon json-event)
  (let* ((ev (canonicalize-event :adapter :session 1000 "test"))
         (json (trace-event->json ev)))
    (true (search "seq_id" json))
    (true (search "1000" json))
    (true (search "ADAPTER" json))
    (true (search "SESSION" json))))

(define-test (event-trace-canon json-diff)
  (let* ((e1 (canonicalize-event :adapter :session 1000 "p1"))
         (s1 (canonicalize-stream (list e1)))
         (s2 (canonicalize-stream (list e1)))
         (diff (trace-diff s1 s2))
         (json (trace-diff->json diff)))
    (true (search "matched" json))
    (true (search ":1," json))))

(define-test (event-trace-canon empty-streams)
  (let* ((s1 (canonicalize-stream nil))
         (s2 (canonicalize-stream nil)))
    (is = 0 (ts-count s1))
    (true (trace-parity-p s1 s2))))

(define-test (event-trace-canon all-event-kinds)
  (let ((kinds '(:session :cron :health :alert :usage :probe :lifecycle)))
    (dolist (k kinds)
      (let ((ev (canonicalize-event :adapter k 1000 "test")))
        (is eq k (tev-event-kind ev))))))

(define-test (event-trace-canon all-source-tags)
  (let ((tags '(:adapter :pipeline :store :harness)))
    (dolist (tag tags)
      (let ((ev (canonicalize-event tag :session 1000 "test")))
        (is eq tag (tev-source-tag ev))))))
