;;; -*- Mode: Lisp; Syntax: Common-Lisp -*-
(in-package #:orrery/harness-tests)

(define-test fixture-corpus-gen)

(define-test (fixture-corpus-gen make-entry)
  (let ((e (make-corpus-entry-from-sample "/api/v1/sessions" :session "{\"ok\":true}" 1000)))
    (is string= "/api/v1/sessions" (ce-endpoint-path e))
    (is eq :session (ce-event-kind e))
    (is = 1000 (ce-timestamp e))
    (true (> (ce-expected-hash e) 0))
    (is string= "{\"ok\":true}" (ce-payload e))))

(define-test (fixture-corpus-gen deterministic-hash)
  (let ((e1 (make-corpus-entry-from-sample "/api/v1/sessions" :session "{\"ok\":true}" 1000))
        (e2 (make-corpus-entry-from-sample "/api/v1/sessions" :session "{\"ok\":true}" 1000)))
    (is = (ce-expected-hash e1) (ce-expected-hash e2))))

(define-test (fixture-corpus-gen different-payloads)
  (let ((e1 (make-corpus-entry-from-sample "/p" :session "a" 0))
        (e2 (make-corpus-entry-from-sample "/p" :session "b" 0)))
    (isnt = (ce-expected-hash e1) (ce-expected-hash e2))))

(define-test (fixture-corpus-gen build-sorted)
  (let* ((e1 (make-corpus-entry-from-sample "/z" :session "p1" 1000))
         (e2 (make-corpus-entry-from-sample "/a" :cron "p2" 2000))
         (e3 (make-corpus-entry-from-sample "/m" :health "p3" 500))
         (corpus (build-corpus (list e1 e2 e3))))
    (is = 3 (cman-entry-count corpus))
    ;; First entry should be /a (alphabetical)
    (is string= "/a" (ce-endpoint-path (first (cman-entries corpus))))
    ;; Last should be /z
    (is string= "/z" (ce-endpoint-path (car (last (cman-entries corpus)))))
    (true (> (cman-checksum corpus) 0))))

(define-test (fixture-corpus-gen build-version-seed)
  (let* ((e (make-corpus-entry-from-sample "/p" :session "x" 0))
         (corpus (build-corpus (list e) :version 5 :seed 42)))
    (is = 5 (cman-version corpus))
    (is = 42 (cman-seed corpus))))

(define-test (fixture-corpus-gen diff-identical)
  (let* ((e1 (make-corpus-entry-from-sample "/a" :session "p1" 0))
         (e2 (make-corpus-entry-from-sample "/b" :cron "p2" 0))
         (c1 (build-corpus (list e1 e2)))
         (c2 (build-corpus (list e1 e2)))
         (diff (diff-corpora c1 c2)))
    (is = 2 (cdiff-unchanged diff))
    (is = 0 (cdiff-added diff))
    (is = 0 (cdiff-removed diff))
    (is = 0 (cdiff-changed diff))
    (true (corpus-stable-p c1 c2))))

(define-test (fixture-corpus-gen diff-added)
  (let* ((e1 (make-corpus-entry-from-sample "/a" :session "p1" 0))
         (e2 (make-corpus-entry-from-sample "/b" :cron "p2" 0))
         (c1 (build-corpus (list e1)))
         (c2 (build-corpus (list e1 e2)))
         (diff (diff-corpora c1 c2)))
    (is = 1 (cdiff-added diff))
    (is = 1 (cdiff-unchanged diff))
    ;; Added-only is still stable (no regressions)
    (true (corpus-stable-p c1 c2))))

(define-test (fixture-corpus-gen diff-removed)
  (let* ((e1 (make-corpus-entry-from-sample "/a" :session "p1" 0))
         (e2 (make-corpus-entry-from-sample "/b" :cron "p2" 0))
         (c1 (build-corpus (list e1 e2)))
         (c2 (build-corpus (list e1)))
         (diff (diff-corpora c1 c2)))
    (is = 1 (cdiff-removed diff))
    (false (corpus-stable-p c1 c2))))

(define-test (fixture-corpus-gen diff-changed)
  (let* ((e1a (make-corpus-entry-from-sample "/a" :session "version-1" 0))
         (e1b (make-corpus-entry-from-sample "/a" :session "version-2" 0))
         (c1 (build-corpus (list e1a)))
         (c2 (build-corpus (list e1b)))
         (diff (diff-corpora c1 c2)))
    (is = 1 (cdiff-changed diff))
    (false (corpus-stable-p c1 c2))))

(define-test (fixture-corpus-gen json-entry)
  (let* ((e (make-corpus-entry-from-sample "/api/v1/sessions" :session "{\"ok\":true}" 1000))
         (json (entry->fixture-json e)))
    (true (search "sessions" json))
    (true (search "SESSION" json))
    (true (search "1000" json))))

(define-test (fixture-corpus-gen json-corpus)
  (let* ((e1 (make-corpus-entry-from-sample "/a" :session "p1" 0))
         (corpus (build-corpus (list e1)))
         (json (corpus->json corpus)))
    (true (search "version" json))
    (true (search "entries" json))
    (true (search "checksum" json))))

(define-test (fixture-corpus-gen json-diff)
  (let* ((e1 (make-corpus-entry-from-sample "/a" :session "p1" 0))
         (c1 (build-corpus (list e1)))
         (c2 (build-corpus (list e1)))
         (diff (diff-corpora c1 c2))
         (json (corpus-diff->json diff)))
    (true (search "unchanged" json))
    (true (search "added" json))))

(define-test (fixture-corpus-gen empty-corpus)
  (let ((corpus (build-corpus nil)))
    (is = 0 (cman-entry-count corpus))
    (is = 1 (cman-version corpus))))

(define-test (fixture-corpus-gen all-event-kinds)
  (let ((kinds '(:session :cron :health :alert :usage :probe :lifecycle)))
    (dolist (k kinds)
      (let ((e (make-corpus-entry-from-sample "/test" k "payload" 0)))
        (is eq k (ce-event-kind e))))))

(define-test (fixture-corpus-gen checksum-deterministic)
  (let* ((e1 (make-corpus-entry-from-sample "/a" :session "p" 0))
         (e2 (make-corpus-entry-from-sample "/b" :cron "q" 0))
         (c1 (build-corpus (list e1 e2)))
         (c2 (build-corpus (list e2 e1))))
    ;; Same entries in different order → same checksum (sorted)
    (is = (cman-checksum c1) (cman-checksum c2))))
