;;; -*- Mode: Lisp; Syntax: Common-Lisp -*-
(in-package #:orrery/harness-tests)

(define-test gate-orchestration-runner)

(define-test (gate-orchestration-runner default-config)
  (let ((cfg (make-default-config :fixture)))
    (is eq :fixture (grc-profile cfg))
    (is = 6 (length (grc-endpoints cfg)))
    (is = 0 (grc-seed cfg))))

(define-test (gate-orchestration-runner default-config-seed)
  (let ((cfg (make-default-config :fixture :seed 42)))
    (is = 42 (grc-seed cfg))))

(define-test (gate-orchestration-runner capture-step)
  (let* ((cfg (make-default-config :fixture))
         (result (run-capture-step cfg)))
    (is eq :pass (gsr-status result))
    (is string= "capture" (gsr-step-name result))
    (is = 6 (length (gsr-artifact result)))
    (true (search "6 endpoints" (gsr-message result)))))

(define-test (gate-orchestration-runner corpus-step)
  (let* ((cfg (make-default-config :fixture))
         (capture (run-capture-step cfg))
         (result (run-corpus-step cfg (gsr-artifact capture))))
    (is eq :pass (gsr-status result))
    (is string= "corpus" (gsr-step-name result))
    (true (typep (gsr-artifact result) 'corpus-manifest))
    (is = 6 (cman-entry-count (gsr-artifact result)))))

(define-test (gate-orchestration-runner parity-identical)
  (let* ((cfg (make-default-config :fixture))
         (capture (run-capture-step cfg))
         (corpus-r (run-corpus-step cfg (gsr-artifact capture)))
         (corpus (gsr-artifact corpus-r))
         (result (run-parity-step corpus corpus)))
    (is eq :pass (gsr-status result))
    (true (search "STABLE" (gsr-message result)))))

(define-test (gate-orchestration-runner parity-regression)
  (let* ((cfg1 (make-default-config :fixture :seed 0))
         (cfg2 (make-gate-run-config
                :profile :fixture
                :endpoints '("/api/v1/sessions" "/api/v1/cron" "/api/v1/health")
                :seed 0))
         (c1 (run-capture-step cfg1))
         (c2 (run-capture-step cfg2))
         (corpus1 (gsr-artifact (run-corpus-step cfg1 (gsr-artifact c1))))
         (corpus2 (gsr-artifact (run-corpus-step cfg2 (gsr-artifact c2))))
         (result (run-parity-step corpus2 corpus1)))
    ;; corpus1 has 6 entries, corpus2 has 3 → removed = 3
    (is eq :fail (gsr-status result))
    (true (search "REGRESSION" (gsr-message result)))))

(define-test (gate-orchestration-runner verdict-all-pass)
  (let* ((s1 (make-gate-step-result :step-name "a" :status :pass))
         (s2 (make-gate-step-result :step-name "b" :status :pass))
         (verdict (run-verdict-step (list s1 s2))))
    (is eq :pass (gsr-status verdict))))

(define-test (gate-orchestration-runner verdict-has-fail)
  (let* ((s1 (make-gate-step-result :step-name "a" :status :pass))
         (s2 (make-gate-step-result :step-name "b" :status :fail))
         (verdict (run-verdict-step (list s1 s2))))
    (is eq :fail (gsr-status verdict))))

(define-test (gate-orchestration-runner verdict-error-wins)
  (let* ((s1 (make-gate-step-result :step-name "a" :status :fail))
         (s2 (make-gate-step-result :step-name "b" :status :error))
         (verdict (run-verdict-step (list s1 s2))))
    (is eq :error (gsr-status verdict))))

(define-test (gate-orchestration-runner full-run-no-baseline)
  (let* ((cfg (make-default-config :fixture))
         (report (execute-gate-run cfg)))
    (is eq :pass (grr-verdict report))
    (is = 4 (grr-step-count report))
    (is = 4 (length (grr-steps report)))))

(define-test (gate-orchestration-runner full-run-with-baseline)
  (let* ((cfg (make-default-config :fixture))
         (first-run (execute-gate-run cfg))
         (corpus (gsr-artifact (second (grr-steps first-run))))
         (second-run (execute-gate-run cfg :baseline corpus)))
    (is eq :pass (grr-verdict second-run))))

(define-test (gate-orchestration-runner json-step)
  (let* ((step (make-gate-step-result :step-name "test" :status :pass :message "ok"))
         (json (gate-step->json step)))
    (true (search "test" json))
    (true (search "PASS" json))
    (true (search "ok" json))))

(define-test (gate-orchestration-runner json-report)
  (let* ((cfg (make-default-config :fixture))
         (report (execute-gate-run cfg))
         (json (gate-run->json report)))
    (true (search "verdict" json))
    (true (search "PASS" json))
    (true (search "FIXTURE" json))
    (true (search "steps" json))))

(define-test (gate-orchestration-runner deterministic-runs)
  (let* ((cfg (make-default-config :fixture :seed 42))
         (r1 (execute-gate-run cfg))
         (r2 (execute-gate-run cfg)))
    (is eq (grr-verdict r1) (grr-verdict r2))
    (is = (grr-step-count r1) (grr-step-count r2))))
