;;; -*- Mode: Lisp; Syntax: Common-Lisp -*-
;;;
;;; policy-algebra-tests.lisp — Tests for Coalton policy algebra
;;; Tests CL-callable functions generated by Coalton.

(in-package #:orrery/harness-tests)

(define-test policy-algebra-tests)

;;; Verify all expected symbols are exported and fbound
(define-test (policy-algebra-tests exported-symbols)
  (true (fboundp 'orrery/coalton/core:combine-decisions))
  (true (fboundp 'orrery/coalton/core:evaluate-policy))
  (true (fboundp 'orrery/coalton/core:merge-policies))
  (true (fboundp 'orrery/coalton/core:decision-permits-p))
  (true (fboundp 'orrery/coalton/core:make-policy))
  (true (fboundp 'orrery/coalton/core:rule-operation))
  (true (fboundp 'orrery/coalton/core:rule-decision)))

;;; Verify constructor symbols exist (enum repr values)
(define-test (policy-algebra-tests constructor-symbols)
  (true (not (null (find-symbol "ALLOW" "ORRERY/COALTON/CORE"))))
  (true (not (null (find-symbol "DENY" "ORRERY/COALTON/CORE"))))
  (true (not (null (find-symbol "ASK" "ORRERY/COALTON/CORE"))))
  (true (not (null (find-symbol "POLICYRULE" "ORRERY/COALTON/CORE"))))
  (true (not (null (find-symbol "POLICYSET" "ORRERY/COALTON/CORE")))))

;;; Verify combine-decisions is callable
(define-test (policy-algebra-tests combine-is-callable)
  (let* ((pkg (find-package "ORRERY/COALTON/CORE"))
         (allow-sym (find-symbol "ALLOW" pkg))
         (deny-sym (find-symbol "DENY" pkg)))
    (true (not (null allow-sym)))
    (true (not (null deny-sym)))
    ;; combine-decisions should be a function
    (true (functionp #'orrery/coalton/core:combine-decisions))))
