;;; unified-closure-gate-cli-tests.lisp

(in-package #:orrery/harness-tests)

(define-test unified-closure-gate-cli-suite)

(define-test (unified-closure-gate-cli-suite emits-acceptance-artifact-with-gate-adapter)
  (let* ((out "/tmp/orrery-unified-closure-acceptance.json")
         (sbcl-bin (orrery/adapter:selected-sbcl-binary))
         (cmd (format nil "WEB_EVIDENCE_DIR=test-results/e2e-regression-matrix/complete/ TUI_EVIDENCE_DIR=test-results/tui-regression-matrix/complete/ UNIFIED_CLOSURE_OUT=~A ~A --eval '(load \"/home/slime/quicklisp/setup.lisp\")' --script ci/check-unified-closure-gate.lisp" out sbcl-bin)))
    (uiop:run-program cmd :ignore-error-status t :output :string :error-output :string)
    (true (probe-file out))
    (let* ((txt (with-open-file (s out :direction :input)
                  (let ((buf (make-string (file-length s))))
                    (read-sequence buf s)
                    buf))))
      (true (search "\"deterministic_verification_command\":" txt))
      (true (search "\"selected_sbcl_binary\":" txt))
      (true (search "\"gate_adapter\":" txt))
      (true (search "\"mcp_tui_lineage_stamp\":" txt))
      (true (search "\"playwright_attestation\":" txt))
      (true (search "\"command_hash\":" txt))
      (true (search "\"transcript_chain_digest\":" txt))
      (true (search "\"missing_scenarios\":" txt)))))

(define-test (unified-closure-gate-cli-suite fails-closed-when-tui-command-drifts)
  (let* ((out "/tmp/orrery-unified-closure-acceptance-drift.json")
         (sbcl-bin (orrery/adapter:selected-sbcl-binary))
         (cmd (format nil "WEB_EVIDENCE_DIR=test-results/e2e-regression-matrix/complete/ TUI_EVIDENCE_DIR=test-results/tui-regression-matrix/complete/ TUI_EVIDENCE_COMMAND='make tui-e2e' UNIFIED_CLOSURE_OUT=~A ~A --eval '(load \"/home/slime/quicklisp/setup.lisp\")' --script ci/check-unified-closure-gate.lisp" out sbcl-bin))
         (res (uiop:run-program cmd :ignore-error-status t :output :string :error-output :string)))
    (declare (ignore res))
    (true (probe-file out))
    (let* ((txt (with-open-file (s out :direction :input)
                  (let ((buf (make-string (file-length s))))
                    (read-sequence buf s)
                    buf))))
      (true (search "\"pass\":false" txt))
      (true (search "\"mcp_tui_lineage_stamp\":" txt))
      (true (search "\"command_match\":false" txt)))))

(define-test (unified-closure-gate-cli-suite fails-closed-when-playwright-command-drifts)
  (let* ((out "/tmp/orrery-unified-closure-acceptance-web-drift.json")
         (sbcl-bin (orrery/adapter:selected-sbcl-binary))
         (cmd (format nil "WEB_EVIDENCE_DIR=test-results/e2e-regression-matrix/complete/ WEB_EVIDENCE_COMMAND='make e2e' TUI_EVIDENCE_DIR=test-results/tui-regression-matrix/complete/ UNIFIED_CLOSURE_OUT=~A ~A --eval '(load \"/home/slime/quicklisp/setup.lisp\")' --script ci/check-unified-closure-gate.lisp" out sbcl-bin))
         (res (uiop:run-program cmd :ignore-error-status t :output :string :error-output :string)))
    (declare (ignore res))
    (true (probe-file out))
    (let* ((txt (with-open-file (s out :direction :input)
                  (let ((buf (make-string (file-length s))))
                    (read-sequence buf s)
                    buf))))
      (true (search "\"pass\":false" txt))
      (true (search "\"playwright_attestation\":" txt))
      (true (search "\"command_match\":false" txt)))))
