(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)
(let* ((root (or (uiop:getenv "WEB_EVIDENCE_DIR") "test-results/e2e-report/"))
       (cmd (or (uiop:getenv "WEB_EVIDENCE_COMMAND") "cd e2e && ./run-e2e.sh"))
       (verdict (orrery/adapter:run-playwright-s1-s6-preflight root cmd)))
  (format t "~A~%" (orrery/adapter:playwright-preflight-verdict->json verdict))
  (unless (orrery/adapter:ppv-pass-p verdict)
    (uiop:quit 1)))
(uiop:quit 0)
