(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)
(let* ((expected (or (uiop:getenv "EXPECTED_TUI_DIR") "test-results/tui-artifacts/"))
       (current (or (uiop:getenv "CURRENT_TUI_DIR") "test-results/tui-artifacts/"))
       (report (orrery/adapter:compare-tui-artifact-bundles expected current)))
  (format t "~A~%" (orrery/adapter:tui-diff-report->json report))
  (unless (orrery/adapter:tdr-pass-p report)
    (uiop:quit 1)))
(uiop:quit 0)
