(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)
(let* ((root (or (uiop:getenv "WEB_EVIDENCE_DIR") "test-results/e2e-report/"))
       (cmd (or (uiop:getenv "WEB_EVIDENCE_COMMAND") "cd e2e && ./run-e2e.sh"))
       (pkg (find-package "ORRERY/ADAPTER"))
       (write-sym (and pkg (find-symbol "WRITE-PLAYWRIGHT-SCENARIO-LEDGER" pkg)))
       (json-sym (and pkg (find-symbol "PLAYWRIGHT-SCENARIO-LEDGER->JSON" pkg)))
       (ledger (and write-sym (funcall write-sym root cmd))))
  (format t "~A~%" (if (and ledger json-sym)
                        (funcall json-sym ledger)
                        "{\"error\":\"playwright-ledger-symbols-missing\"}"))
  (unless ledger (uiop:quit 1)))
(uiop:quit 0)
