;;; check-epic34-closure-gate.lisp — deny Epic 3/4 closure without required evidence

(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")

(defun getenv-or (name fallback)
  (or (uiop:getenv name) fallback))

(handler-case
    (progn
      (asdf:load-system :agent-orrery)
      (let* ((web-dir (getenv-or "WEB_EVIDENCE_DIR" "test-results/e2e-report/"))
             (web-cmd (getenv-or "WEB_EVIDENCE_COMMAND" "cd e2e && ./run-e2e.sh"))
             (tui-dir (getenv-or "TUI_EVIDENCE_DIR" "test-results/tui-artifacts/"))
             (tui-cmd (getenv-or "TUI_EVIDENCE_COMMAND" "cd e2e-tui && ./run-tui-e2e-t1-t6.sh"))
             (pkg (find-package "ORRERY/ADAPTER"))
             (eval-sym (and pkg (find-symbol "EVALUATE-EPIC34-CLOSURE-GATE" pkg)))
             (ok-sym (and pkg (find-symbol "ECGR-OVERALL-PASS-P" pkg)))
             (json-sym (and pkg (find-symbol "EPIC-CLOSURE-GATE-RESULT->JSON" pkg)))
             (matrix-eval-sym (and pkg (find-symbol "EVALUATE-PROTOCOL-EVIDENCE-MATRIX" pkg)))
             (matrix-ok-sym (and pkg (find-symbol "PMREP-OVERALL-PASS-P" pkg)))
             (matrix-json-sym (and pkg (find-symbol "PROTOCOL-MATRIX-REPORT->JSON" pkg)))
             (gap-eval-sym (and pkg (find-symbol "EXPLAIN-PROTOCOL-EVIDENCE-GAPS" pkg)))
             (gap-ok-sym (and pkg (find-symbol "PEGR-CLOSURE-PASS-P" pkg)))
             (gap-json-sym (and pkg (find-symbol "PROTOCOL-EVIDENCE-GAP-REPORT->JSON" pkg)))
             (res (and eval-sym (funcall eval-sym web-dir web-cmd tui-dir tui-cmd)))
             (matrix-res (and matrix-eval-sym (funcall matrix-eval-sym web-dir web-cmd tui-dir tui-cmd)))
             (gap-res (and gap-eval-sym (funcall gap-eval-sym web-dir web-cmd tui-dir tui-cmd)))
             (ok (and res ok-sym (funcall ok-sym res)
                      matrix-res matrix-ok-sym (funcall matrix-ok-sym matrix-res)
                      gap-res gap-ok-sym (funcall gap-ok-sym gap-res))))
        (format t "~A~%" (if (and res json-sym)
                              (funcall json-sym res)
                              "{\"error\":\"closure-gate-symbols-missing\"}"))
        (format t "~A~%" (if (and matrix-res matrix-json-sym)
                              (funcall matrix-json-sym matrix-res)
                              "{\"error\":\"protocol-matrix-symbols-missing\"}"))
        (format t "~A~%" (if (and gap-res gap-json-sym)
                              (funcall gap-json-sym gap-res)
                              "{\"error\":\"protocol-evidence-gap-symbols-missing\"}"))
        (unless ok
          (error "Epic 3/4 closure gate failed (or protocol matrix/evidence-gap denied)"))))
  (error (e)
    (format *error-output* "~&EPIC34 CLOSURE GATE ERROR: ~A~%" e)
    (uiop:quit 1)))

(uiop:quit 0)
