(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)
(let* ((artifact (or (uiop:getenv "TUI_EVIDENCE_DIR") "test-results/tui-artifacts/"))
       (command (or (uiop:getenv "TUI_EVIDENCE_COMMAND") "cd e2e-tui && ./run-tui-e2e-t1-t6.sh"))
       (out (or (uiop:getenv "TUI_LOCK_OUT") "test-results/tui-artifacts/epic3-manifest-lock.json"))
       (ledger-out (or (uiop:getenv "TUI_LEDGER_OUT") "test-results/tui-artifacts/t1-t6-scenario-ledger.json"))
       (ledger-prior (or (uiop:getenv "TUI_LEDGER_PRIOR") (format nil "~A.sexp" ledger-out)))
       (lock (orrery/adapter:write-epic3-manifest-lock artifact command out))
       (ledger (orrery/adapter:write-tui-scenario-ledger artifact command ledger-out :previous-ledger-path ledger-prior)))
  (format t "~A~%" (orrery/adapter:evidence-manifest-lock->json lock))
  (format t "~A~%" (orrery/adapter:tui-scenario-ledger->json ledger))
  (unless (and (orrery/adapter:eml-pass-p lock)
               (orrery/adapter:tsl-continuity-pass-p ledger))
    (uiop:quit 1)))
(uiop:quit 0)
