(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)
(let* ((artifact (or (uiop:getenv "TUI_EVIDENCE_DIR") "test-results/tui-artifacts/"))
       (command (or (uiop:getenv "TUI_EVIDENCE_COMMAND") "make e2e-tui"))
       (out (or (uiop:getenv "TUI_LOCK_OUT") "test-results/tui-artifacts/epic3-manifest-lock.json"))
       (lock (orrery/adapter:write-epic3-manifest-lock artifact command out)))
  (format t "~A~%" (orrery/adapter:evidence-manifest-lock->json lock))
  (unless (orrery/adapter:eml-pass-p lock) (uiop:quit 1)))
(uiop:quit 0)
