(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)

(let* ((base (or (uiop:getenv "WEB_FIXTURE_MATRIX_DIR") "test-results/e2e-regression-matrix/"))
       (complete-dir (namestring (merge-pathnames "complete/" (pathname base))))
       (gapped-dir (namestring (merge-pathnames "gapped/" (pathname base))))
       (cmd "cd e2e && ./run-e2e.sh")
       (bad-cmd "make e2e")
       (complete-gen (orrery/adapter:generate-playwright-fixture-set complete-dir :complete))
       (gapped-gen (orrery/adapter:generate-playwright-fixture-set gapped-dir :gapped))
       (complete-gate (orrery/adapter:evaluate-epic4-fail-closed-gate complete-dir cmd))
       (gapped-gate (orrery/adapter:evaluate-epic4-fail-closed-gate gapped-dir bad-cmd))
       (ok (and (orrery/adapter:pfgr-pass-p complete-gen)
                (orrery/adapter:pfgr-pass-p gapped-gen)
                (orrery/adapter:e4fcr-pass-p complete-gate)
                (not (orrery/adapter:e4fcr-pass-p gapped-gate)))))
  (format t "{\"ok\":~A,\"complete\":~A,\"gapped\":~A}~%"
          (if ok "true" "false")
          (orrery/adapter:epic4-fail-closed-result->json complete-gate)
          (orrery/adapter:epic4-fail-closed-result->json gapped-gate))
  (unless ok (uiop:quit 1)))

(uiop:quit 0)
