(load #P"/home/slime/quicklisp/setup.lisp")
(require "asdf")
(asdf:load-system :agent-orrery)

(let* ((base (or (uiop:getenv "TUI_FIXTURE_MATRIX_DIR") "test-results/tui-regression-matrix/"))
       (complete-dir (namestring (merge-pathnames "complete/" (pathname base))))
       (gapped-dir (namestring (merge-pathnames "gapped/" (pathname base))))
       (cmd "cd e2e-tui && ./run-tui-e2e-t1-t6.sh")
       (bad-cmd "make e2e-tui")
       (complete-gen (orrery/adapter:generate-tui-fixture-set complete-dir :complete))
       (gapped-gen (orrery/adapter:generate-tui-fixture-set gapped-dir :gapped))
       (complete-gate (orrery/adapter:evaluate-mcp-tui-scorecard-gate complete-dir cmd))
       (gapped-gate (orrery/adapter:evaluate-mcp-tui-scorecard-gate gapped-dir cmd))
       (drift-gate (orrery/adapter:evaluate-mcp-tui-scorecard-gate complete-dir bad-cmd))
       (ok (and (orrery/adapter:tfgr-pass-p complete-gen)
                (orrery/adapter:tfgr-pass-p gapped-gen)
                (orrery/adapter:mtsr-pass-p complete-gate)
                (not (orrery/adapter:mtsr-pass-p gapped-gate))
                (not (orrery/adapter:mtsr-pass-p drift-gate)))))
  (format t "{\"ok\":~A,\"complete\":~A,\"gapped\":~A,\"command_drift\":~A}~%"
          (if ok "true" "false")
          (orrery/adapter:mcp-tui-scorecard-result->json complete-gate)
          (orrery/adapter:mcp-tui-scorecard-result->json gapped-gate)
          (orrery/adapter:mcp-tui-scorecard-result->json drift-gate))
  (unless ok (uiop:quit 1)))

(uiop:quit 0)
