(ql:quickload "agent-orrery" :silent t)
(in-package :orrery/adapter)
(let* ((journal (make-empty-journal))
       (pack (assemble-rerun-pack journal))
       (cv (verify-t1-t6-closure pack)))
  (assert (not (closure-verdict-pass-p cv)) nil "empty journal should not pass")
  (assert (eq (verdict-verdict cv) :incomplete) nil "empty journal should be :incomplete")
  (assert (verdict-command-canonical-p cv) nil "canonical command should be valid")
  (assert (= 6 (length (verdict-findings cv))) nil "should have 6 findings")
  (format t "PASS: fail-closed verifier smoke test (verdict=~A)~%" (verdict-verdict cv)))
