(ql:quickload "agent-orrery" :silent t)
(in-package :orrery/adapter)
(let* ((j (make-empty-journal))
       (p (assemble-rerun-pack j)))
  (assert (not (journal-complete-p j)) nil "journal should not be complete initially")
  (assert (= 6 (length (journal-missing-scenarios j))) nil "should have 6 missing scenarios")
  (assert (eq :incomplete (pack-verdict p)) nil "pack verdict should be :incomplete")
  (assert (command-lock-valid-p (pack-command-lock p)) nil "command-lock should be valid")
  (format t "PASS: replay-journal + command-lock-packager smoke test~%"))
